//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeDomStudy {
	using System;
	
	
	public class GeneratedClass {
		
		public void SayHello() {
			Console.WriteLine("Hello babacan");
		}
		
		public static int Add(params int[] numbers) {
			int sum = 0;
			for (int i = 0; (i < numbers.Length); i = (i + 1)) {
				sum = (sum + i);
			}
			return sum;
		}
		
		public static int Add2(params int[] numbers) {
			int sum = 0;
			Array.ForEach(numbers, number=>sum+=number);
			return sum;
		}
	}
}
